fix(hardcoded-buckets): Add error if bucket not found or empty

diff --git a/argo/gwas-workflows/integration-test-genesis-association.buckets.template.yml b/argo/gwas-workflows/integration-test-genesis-association.buckets.template.yml
--- a/argo/gwas-workflows/integration-test-genesis-association.buckets.template.yml
+++ b/argo/gwas-workflows/integration-test-genesis-association.buckets.template.yml
@@ -204,8 +204,13 @@ spec:
         imagePullPolicy: IfNotPresent
         command: [/bin/sh]
         source: |
-          echo "Downloadable bucket found: $DOWNLOADABLE_BUCKET"
-          echo "$DOWNLOADABLE_BUCKET" > /mnt/vol/downloadable_bucket.txt
+          if [ -z $DOWNLOADABLE_BUCKET ]; then
+            echo "Downloadable bucket is not found or set to empty string"
+            exit 1
+          else
+            echo "Downloadable bucket found: $DOWNLOADABLE_BUCKET"
+            echo "$DOWNLOADABLE_BUCKET" > /mnt/vol/downloadable_bucket.txt
+          fi
         volumeMounts:
           - name: workdir
             mountPath: /mnt/vol
