Merge qa templates to the main one

diff --git a/argo/gwas-workflows/integration-test-genesis-association.template.yml b/argo/gwas-workflows/integration-test-genesis-association.template.yml
--- a/argo/gwas-workflows/integration-test-genesis-association.template.yml
+++ b/argo/gwas-workflows/integration-test-genesis-association.template.yml
@@ -1,7 +1,11 @@
 apiVersion: argoproj.io/v1alpha1
 kind: WorkflowTemplate
 metadata:
-  name: gwas-template-integration-test
+  name: gwas-template-test-buckets
+    annotations:
+    version: 1.0.0
+    description: |
+      Merge all qa templates to the latest
 spec:
   ttlStrategy:
     secondsAfterCompletion: 10
@@ -43,6 +47,8 @@ spec:
           - name: gds_files
       dag:
         tasks:
+          - name: get-downloadable-bucket
+            template: get-downloadable-bucket          
           - name: pass-variables
             template: pass-variables
             arguments:
@@ -119,7 +125,7 @@ spec:
                   from: "{{tasks.process-variables.outputs.artifacts.variables_validated}}"
           - name: get-attrition-csv
             template: get-attrition-csv
-            dependencies: [process-variables]
+            dependencies: [get-downloadable-bucket, process-variables]
             arguments:
               parameters:
                 - name: internal_api_env
@@ -132,33 +138,104 @@ spec:
                   value: "{{inputs.parameters.source_population_cohort}}"
                 - name: outcome
                   value: "{{inputs.parameters.outcome}}"
+                - name: downloadable_bucket
+                  value: "{{tasks.get-downloadable-bucket.outputs.parameters.downloadable_bucket}}"
               artifacts:
                 - name: variables_validated
                   from: "{{tasks.process-variables.outputs.artifacts.variables_validated}}"
+          - name: create-figure
+            template: create-figure
+            dependencies: [get-downloadable-bucket, get-attrition-csv]
+            arguments:
+              parameters:
+                - name: downloadable_bucket
+                  value: "{{tasks.get-downloadable-bucket.outputs.parameters.downloadable_bucket}}"
           - name: archive-outputs
             template: archive-outputs
-            dependencies: [get-gwas-metadata, get-attrition-csv]
+            dependencies: [get-downloadable-bucket, get-gwas-metadata, get-attrition-csv]
             arguments:
               parameters:
                 - name: out_prefix
                   value: "{{inputs.parameters.out_prefix}}"
+                - name: downloadable_bucket
+                  value: "{{tasks.get-downloadable-bucket.outputs.parameters.downloadable_bucket}}"
               artifacts:
                 - name: attrition_csvs
                   from: "{{tasks.get-attrition-csv.outputs.artifacts.attrition_table_directory}}"
                 - name: gwas_metadata
                   from: "{{tasks.get-gwas-metadata.outputs.artifacts.gwas_metadata}}"
+          - name: generate-pheweb-json
+            dependencies: [get-downloadable-bucket]
+            template: pheweb-json
+            arguments:
+              parameters:
+                - name: out_prefix
+                  value: "{{inputs.parameters.out_prefix}}"
+                - name: downloadable_bucket
+                  value: "{{tasks.get-downloadable-bucket.outputs.parameters.downloadable_bucket}}"
+              artifacts:
+                - name: pheweb_input_tsv
+                  s3:
+                    key: "public-pheweb-input-tsv/meta_Single_lgddimer.for_pheweb.tsv.gz"
           - name: create-indexd-record
             template: create-indexd-record
-            dependencies: [archive-outputs]
+            dependencies: [get-downloadable-bucket, archive-outputs, create-figure, generate-pheweb-json]
             arguments:
               parameters:
                 - name: arborist_resource
                   value: "/programs/DEV/projects/test"
                 - name: internal_api_env
                   value: "{{inputs.parameters.internal_api_env}}"
+                - name: out_prefix
+                  value: "{{inputs.parameters.out_prefix}}"
+                - name: downloadable_bucket
+                  value: "{{tasks.get-downloadable-bucket.outputs.parameters.downloadable_bucket}}"
               artifacts:
                 - name: gwas_archive
                   from: "{{tasks.archive-outputs.outputs.artifacts.gwas_archive}}"
+                - name: simulated_plot
+                  from: "{{tasks.create-figure.outputs.artifacts.simulated_plot}}"
+                - name: attrition_json
+                  from: "{{tasks.get-attrition-csv.outputs.artifacts.attrition_table_json}}"
+                - name: manhattan_pheweb_json
+                  from: "{{tasks.generate-pheweb-json.outputs.artifacts.manhattan_json_for_pheweb}}"
+                - name: qq_pheweb_json
+                  from: "{{tasks.generate-pheweb-json.outputs.artifacts.qq_json_for_pheweb}}"
+
+    - name: get-downloadable-bucket
+      script:
+        image: quay.io/cdis/alpine-jq:latest
+        imagePullPolicy: IfNotPresent
+        command: [/bin/sh]
+        source: |
+          if [ -z $DOWNLOADABLE_BUCKET ]; then
+            echo "Downloadable bucket is not found or set to empty string"
+            exit 1
+          else
+            echo "Downloadable bucket found: $DOWNLOADABLE_BUCKET"
+            echo "$DOWNLOADABLE_BUCKET" > /mnt/vol/downloadable_bucket.txt
+          fi
+        volumeMounts:
+          - name: workdir
+            mountPath: /mnt/vol
+        resources:
+          requests:
+            cpu: 250m
+            memory: 500Mi
+          limits:
+            cpu: 500m
+            memory: 1Gi
+        env:
+        - name: DOWNLOADABLE_BUCKET  # name of env var
+          valueFrom:
+            secretKeyRef:
+              name: argo-template-values-secret     # name of an existing k8s secret
+              key: DOWNLOADABLE_BUCKET     # 'key' subcomponent of the secret      
+      outputs:
+        parameters:
+          - name: downloadable_bucket
+            valueFrom:
+              path: "/mnt/vol/downloadable_bucket.txt" 
 
     - name: pass-variables
       inputs:
@@ -192,7 +269,7 @@ spec:
           - name: variables_json
             path: /mnt/vol/variables.json
       script:
-        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.0.1
+        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.2.3
         imagePullPolicy: IfNotPresent
         command: ["/bin/bash"]
         source: |
@@ -244,7 +321,7 @@ spec:
           - name: variables_with_hare_json
             path: /mnt/vol/variables_with_hare.json
       script:
-        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.0.1
+        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.2.3
         imagePullPolicy: IfNotPresent
         command: [/bin/bash]
         source: |
@@ -337,7 +414,7 @@ spec:
           - name: variables_validated
             path: /mnt/vol/variables_validated.json
       script:
-        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.0.1
+        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.2.3
         imagePullPolicy: IfNotPresent
         command: [/bin/bash]
         source: |
@@ -376,11 +453,12 @@ spec:
           - name: hare_concept_id
           - name: source_population_cohort
           - name: outcome
+          - name: downloadable_bucket
         artifacts:
           - name: variables_validated
             path: /mnt/vol/variables_validated.json
       script:
-        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.0.1
+        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.2.3
         imagePullPolicy: IfNotPresent
         command: ["/bin/bash"]
         source: |
@@ -391,7 +469,8 @@ spec:
           --outcome '{{inputs.parameters.outcome}}' \
           --variables_json {{inputs.artifacts.variables_validated.path}} \
           --prefixed_breakdown_concept_id {{inputs.parameters.hare_concept_id}} \
-          --output_prefix /mnt/vol/attrition_csvs/{{workflow.name}}
+          --output_csv_prefix /mnt/vol/attrition_csvs/{{workflow.name}} \
+          --output_combined_json /mnt/vol/{{workflow.name}}.attrition.json
         volumeMounts:
           - name: workdir
             mountPath: /mnt/vol
@@ -405,12 +484,74 @@ spec:
             archive:
               none: {}
             s3:
-                key: "{{workflow.name}}/{{pod.name}}/attrition_csvs"
+              key: "{{workflow.name}}/attrition_csvs"
+          - name: attrition_table_json
+            path: /mnt/vol/{{workflow.name}}.attrition.json
+            archive:
+              none: {}
+            s3:
+              endpoint: s3.amazonaws.com
+              bucket: "{{inputs.parameters.downloadable_bucket}}"
+              key: "{{workflow.name}}/{{workflow.name}}.attrition.json"
+              accessKeySecret:
+                name: argo-s3-creds
+                key: AccessKeyId
+              secretKeySecret:
+                name: argo-s3-creds
+                key: SecretAccessKey
+
+    - name: create-figure
+      inputs:
+        parameters:
+          - name: downloadable_bucket
+      script:
+        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/topmed-master:2.12.0
+        imagePullPolicy: IfNotPresent
+        securityContext:
+          runAsUser: 0
+        command: [Rscript]
+        source: |
+          library(ggplot2)
+
+          sim.dat <- as.data.frame(rnorm(1000))
+          names(sim.dat) <- c("X")
+          head(sim.dat)
+
+          p <- ggplot(sim.dat, aes(x=X)) +
+            geom_histogram(bins=30)
+          ggsave(filename="/mnt/vol/test.png", plot=p, width=10, height=5)
+        volumeMounts:
+          - name: workdir
+            mountPath: /mnt/vol
+        resources:
+          requests:
+            cpu: 250m
+            memory: 1Gi
+          limits:
+            cpu: 1000m
+            memory: 8Gi
+      outputs:
+        artifacts:
+          - name: simulated_plot
+            path: "/mnt/vol/test.png"
+            archive:
+              none: {}
+            s3:
+              endpoint: s3.amazonaws.com
+              bucket: "{{inputs.parameters.downloadable_bucket}}"
+              key: "{{workflow.name}}/test.png"
+              accessKeySecret:
+                name: argo-s3-creds
+                key: AccessKeyId
+              secretKeySecret:
+                name: argo-s3-creds
+                key: SecretAccessKey
 
     - name: archive-outputs
       inputs:
         parameters:
           - name: out_prefix
+          - name: downloadable_bucket
         artifacts:
           - name: attrition_csvs
             mode: 0777
@@ -442,8 +583,64 @@ spec:
               none: {}
             s3:
               endpoint: s3.amazonaws.com
-              bucket: second-argo-bucket
+              bucket: "{{inputs.parameters.downloadable_bucket}}"
               key: "{{workflow.name}}/{{workflow.name}}.zip"
+              accessKeySecret:
+                name: argo-s3-creds
+                key: AccessKeyId
+              secretKeySecret:
+                name: argo-s3-creds
+                key: SecretAccessKey
+
+    - name: pheweb-json
+      inputs:
+        parameters:
+          - name: out_prefix
+          - name: downloadable_bucket
+        artifacts:
+          - name: pheweb_input_tsv
+            path: /mnt/vol/pheweb.tsv.gz
+      script:
+        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.2.3
+        imagePullPolicy: IfNotPresent
+        command: ["/bin/bash"]
+        source: |
+          /env/bin/vadc-gwas-tools GetPheWebPlotJson \
+          --in_tsv {{inputs.artifacts.pheweb_input_tsv.path}} \
+          --out_json /mnt/vol/{{inputs.parameters.out_prefix}}.pheweb.manhattan.json \
+          --out_plot_type manhattan
+
+          /env/bin/vadc-gwas-tools GetPheWebPlotJson \
+          --in_tsv {{inputs.artifacts.pheweb_input_tsv.path}} \
+          --out_json /mnt/vol/{{inputs.parameters.out_prefix}}.pheweb.qq.json \
+          --out_plot_type qq
+        volumeMounts:
+          - name: workdir
+            mountPath: /mnt/vol
+      outputs:
+        artifacts:
+          - name: manhattan_json_for_pheweb
+            path: /mnt/vol/{{inputs.parameters.out_prefix}}.pheweb.manhattan.json
+            archive:
+              none: {}
+            s3:
+              endpoint: s3.amazonaws.com
+              bucket: "{{inputs.parameters.downloadable_bucket}}"
+              key: "{{workflow.name}}/{{inputs.parameters.out_prefix}}.pheweb.manhattan.json"
+              accessKeySecret:
+                name: argo-s3-creds
+                key: AccessKeyId
+              secretKeySecret:
+                name: argo-s3-creds
+                key: SecretAccessKey
+          - name: qq_json_for_pheweb
+            path: /mnt/vol/{{inputs.parameters.out_prefix}}.pheweb.qq.json
+            archive:
+              none: {}
+            s3:
+              endpoint: s3.amazonaws.com
+              bucket: "{{inputs.parameters.downloadable_bucket}}"
+              key: "{{workflow.name}}/{{inputs.parameters.out_prefix}}.pheweb.qq.json"
               accessKeySecret:
                 name: argo-s3-creds
                 key: AccessKeyId
@@ -456,18 +653,53 @@ spec:
         parameters:
           - name: arborist_resource
           - name: internal_api_env
+          - name: out_prefix
+          - name: downloadable_bucket
         artifacts:
           - name: gwas_archive
             path: "/mnt/vol/{{workflow.name}}.zip"
-      container:
-        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.0.1
+          - name: simulated_plot
+            path: "/mnt/vol/test.png"
+          - name: attrition_json
+            path: "/mnt/vol/{{workflow.name}}.attrition.json"
+          - name: manhattan_pheweb_json
+            path: "/mnt/vol/pheweb.manhattan.json"
+          - name: qq_pheweb_json
+            path: "/mnt/vol/pheweb.qq.json"
+      script:
+        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/vadc-gwas-tools:1.2.3
         imagePullPolicy: IfNotPresent
-        command: ["/bin/bash", "-c"]
-        args: ["/env/bin/vadc-gwas-tools CreateIndexdRecord \
-                --gwas_archive {{inputs.artifacts.gwas_archive.path}} \
-                --s3_uri s3://second-argo-bucket/{{workflow.name}}/{{workflow.name}}.zip \
-                --arborist_resource {{inputs.parameters.arborist_resource}} \
-                -o /mnt/vol/did.json"]
+        command: [/bin/bash]
+        source: |
+          /env/bin/vadc-gwas-tools CreateIndexdRecord \
+          --gwas_archive {{inputs.artifacts.gwas_archive.path}} \
+          --s3_uri s3://{{inputs.parameters.downloadable_bucket}}/{{workflow.name}}/{{workflow.name}}.zip \
+          --arborist_resource {{inputs.parameters.arborist_resource}} \
+          -o /mnt/vol/did_archive.json
+
+          /env/bin/vadc-gwas-tools CreateIndexdRecord \
+          --gwas_archive {{inputs.artifacts.simulated_plot.path}} \
+          --s3_uri s3://{{inputs.parameters.downloadable_bucket}}/{{workflow.name}}/test.png \
+          --arborist_resource {{inputs.parameters.arborist_resource}} \
+          -o /mnt/vol/did_plot.json
+
+          /env/bin/vadc-gwas-tools CreateIndexdRecord \
+          --gwas_archive {{inputs.artifacts.attrition_json.path}} \
+          --s3_uri s3://{{inputs.parameters.downloadable_bucket}}/{{workflow.name}}/{{workflow.name}}.attrition.json \
+          --arborist_resource {{inputs.parameters.arborist_resource}} \
+          -o /mnt/vol/did_attrition.json
+
+          /env/bin/vadc-gwas-tools CreateIndexdRecord \
+          --gwas_archive {{inputs.artifacts.manhattan_pheweb_json.path}} \
+          --s3_uri s3://{{inputs.parameters.downloadable_bucket}}/{{workflow.name}}/{{inputs.parameters.out_prefix}}.pheweb.manhattan.json \
+          --arborist_resource {{inputs.parameters.arborist_resource}} \
+          -o /mnt/vol/did_pheweb_manhattan_json.json
+
+          /env/bin/vadc-gwas-tools CreateIndexdRecord \
+          --gwas_archive {{inputs.artifacts.qq_pheweb_json.path}} \
+          --s3_uri s3://{{inputs.parameters.downloadable_bucket}}/{{workflow.name}}/{{inputs.parameters.out_prefix}}.pheweb.qq.json \
+          --arborist_resource {{inputs.parameters.arborist_resource}} \
+          -o /mnt/vol/did_pheweb_qq_json.json
         env:
           - name: GEN3_ENVIRONMENT
             value: "{{inputs.parameters.internal_api_env}}"
@@ -495,5 +727,21 @@ spec:
         parameters:
           - name: gwas_archive_index
             valueFrom:
-              path: /mnt/vol/did.json
+              path: /mnt/vol/did_archive.json
             globalName: gwas_archive_index
+          - name: simulated_plot_index
+            valueFrom:
+              path: /mnt/vol/did_plot.json
+            globalName: manhattan_plot_index
+          - name: attrition_json_index
+            valueFrom:
+              path: /mnt/vol/did_attrition.json
+            globalName: attrition_json_index
+          - name: pheweb_manhattan_json_index
+            valueFrom:
+              path: /mnt/vol/did_pheweb_manhattan_json.json
+            globalName: pheweb_manhattan_json_index
+          - name: pheweb_qq_json_index
+            valueFrom:
+              path: /mnt/vol/did_pheweb_qq_json.json
+            globalName: pheweb_qq_json_index
